[project]
name = "quotes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ebooklib>=0.19",
    "opencc>=1.1.9",
    "pyperclip>=1.9.0",
]
